### ISSUE TITLE
use new supported version of maknz/slack

### ISSUE THREAD

**Issue by alek13** [alexeevdv/yii2-log-slack#1]
Hi @alexeevdv .

package `maknz/slack` was abandoned.

please use in your package new supported version `alek13/slack` (forked from maknz).

more: https://medium.com/@alek13.me/reincarnation-of-popular-php-package-for-slack-cb2e8db98a91
in russian: http://phpprofi.ru/blogs/post/93

**Comment by alexeevdv** [comment]
I don't see any reason to change it now. This package works great and does it job pretty well. But anyway thanks for your efforts
